create table volunteer (
	id BIGINT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	phone_number VARCHAR(50),
	affiliation VARCHAR(18),
	non_english_language VARCHAR(50),
	first_time_volunteer VARCHAR(50),
	volunteering_for_credit VARCHAR(50),
	hipaa_training VARCHAR(50),
	role VARCHAR(6)
);
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (1, 'Brand', 'Cant', '575-518-1779', 'Fuqua', 'West Frisian', true, true, false, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (2, 'Merry', 'Le Blond', '366-940-9545', 'School_of_Medicine', 'Indonesian', true, true, true, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (3, 'Hogan', 'Kilfether', '984-527-8834', 'Faculty/Staff', 'Chinese', false, true, false, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (4, 'Rayshell', 'Rappport', '891-755-9855', 'Fuqua', 'Nepali', false, true, false, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (5, 'Currey', 'Gronaver', '656-208-4313', 'Fuqua', 'Irish Gaelic', true, true, true, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (6, 'Howard', 'Gilluley', '940-564-4920', 'School_of_Medicine', 'Haitian Creole', false, true, true, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (7, 'Nowell', 'Lidgley', '881-821-9539', 'Faculty/Staff', 'Yiddish', true, true, false, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (8, 'Johan', 'Baline', '693-309-8499', 'Faculty/Staff', 'Zulu', false, true, true, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (9, 'Curtis', 'Poles', '593-745-3072', 'School_of_Medicine', 'Thai', true, true, false, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (10, 'Frank', 'Rawet', '639-364-2223', 'School_of_Medicine', 'Swati', false, true, false, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (11, 'Remington', 'Rumney', '387-203-5453', 'Fuqua', 'Fijian', false, true, false, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (12, 'Debbie', 'Eslinger', '112-164-3299', 'School_of_Medicine', 'Somali', false, false, false, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (13, 'Dulcy', 'Brawn', '670-253-8492', 'Alum', 'English', true, true, false, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (14, 'Manolo', 'Samworth', '615-118-0193', 'Undergrad', 'Kazakh', true, true, true, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (15, 'Doreen', 'Coull', '700-822-2673', 'Undergrad', 'Romanian', false, true, true, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (16, 'Aldric', 'Pretorius', '502-130-7114', 'Faculty/Staff', 'Somali', true, true, true, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (17, 'Jimmy', 'Taylo', '771-798-4856', 'Undergrad', 'Albanian', true, false, false, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (18, 'Abagail', 'Gwilliams', '357-918-0160', 'Alum', 'Arabic', false, false, true, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (19, 'Holli', 'Josephsen', '427-767-6619', 'Alum', 'Tswana', false, false, true, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (20, 'Zonda', 'Creavan', '763-390-1149', 'Faculty/Staff', 'Finnish', false, false, false, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (21, 'Jerry', 'Dallyn', '132-707-1099', 'School_of_Medicine', 'Oriya', true, false, true, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (22, 'Reinwald', 'Grocock', '111-346-6875', 'Fuqua', 'Montenegrin', false, true, true, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (23, 'Verena', 'Spyby', '889-223-4199', 'School_of_Medicine', 'Albanian', true, false, false, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (24, 'Chrotoem', 'Normington', '960-291-9692', 'Fuqua', 'Montenegrin', false, false, true, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (25, 'Leo', 'Dmytryk', '701-954-0609', 'School_of_Medicine', 'Malagasy', true, true, true, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (26, 'Casar', 'Clemenzi', '111-101-6163', 'Alum', 'Assamese', false, false, false, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (27, 'Patrizius', 'Yglesia', '719-599-8385', 'Faculty/Staff', 'Czech', true, true, true, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (28, 'Lira', 'Klimontovich', '710-921-1176', 'Faculty/Staff', 'Zulu', false, false, true, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (29, 'Kandace', 'Aspenlon', '594-684-3874', 'Fuqua', 'Czech', true, true, false, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (30, 'Holly', 'Matteacci', '591-462-9538', 'Faculty/Staff', 'Ndebele', false, false, false, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (31, 'Isa', 'Conklin', '843-402-6293', 'Faculty/Staff', 'Chinese', true, true, true, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (32, 'Martino', 'Grain', '134-933-4649', 'School_of_Medicine', 'Khmer', true, false, true, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (33, 'Randa', 'Sabey', '647-269-1595', 'School_of_Medicine', 'New Zealand Sign Language', false, false, true, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (34, 'Scarlett', 'Planque', '833-586-0329', 'Alum', 'Punjabi', false, false, false, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (35, 'Amelia', 'McCallister', '989-342-9489', 'Faculty/Staff', 'Korean', true, false, false, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (36, 'Kelcy', 'Grabban', '593-213-3375', 'Undergrad', 'Hungarian', true, false, false, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (37, 'Archy', 'O''Bradden', '822-365-8328', 'Alum', 'Portuguese', false, false, false, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (38, 'Retha', 'Nelsey', '933-675-2484', 'Undergrad', 'Marathi', true, true, false, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (39, 'John', 'Bartolacci', '141-825-9470', 'Fuqua', 'Dutch', false, false, true, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (40, 'Rycca', 'Strewther', '866-497-4875', 'Undergrad', 'Assamese', false, true, false, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (41, 'Fleur', 'Byneth', '798-853-2441', 'School_of_Medicine', 'Catalan', true, false, false, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (42, 'Noby', 'Kale', '474-869-8970', 'Fuqua', 'English', true, true, false, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (43, 'Antonino', 'Creffeild', '719-720-5383', 'Fuqua', 'Khmer', false, true, true, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (44, 'Parsifal', 'McNickle', '580-404-2077', 'Fuqua', 'Nepali', true, true, true, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (45, 'Emelia', 'Epsley', '145-760-2705', 'Fuqua', 'Romanian', false, true, false, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (46, 'Teresa', 'Idiens', '202-873-9221', 'Undergrad', 'Japanese', false, true, true, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (47, 'Brad', 'Deguara', '923-156-8236', 'Faculty/Staff', 'Guaraní', true, false, true, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (48, 'Sandro', 'Branthwaite', '177-307-6523', 'Fuqua', 'Aymara', true, true, false, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (49, 'Lazarus', 'Sawkins', '727-452-1496', 'Alum', 'Gagauz', false, false, false, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (50, 'Fraser', 'Lude', '899-895-2955', 'School_of_Medicine', 'Afrikaans', true, true, true, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (51, 'Judie', 'Wilcher', '971-452-6276', 'Faculty/Staff', 'Montenegrin', true, true, true, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (52, 'Bobby', 'Larimer', '438-322-9540', 'Fuqua', 'Gagauz', false, true, true, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (53, 'Curcio', 'Benoi', '609-683-5971', 'Fuqua', 'Danish', false, true, true, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (54, 'Brigitta', 'Johansson', '416-593-8118', 'Faculty/Staff', 'Kashmiri', true, false, false, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (55, 'Sayers', 'Oneile', '781-211-6598', 'Alum', 'Bislama', true, false, true, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (56, 'Tandy', 'Cardinale', '908-148-2539', 'Fuqua', 'Pashto', false, false, true, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (57, 'Dagmar', 'Juschka', '258-900-9343', 'School_of_Medicine', 'Belarusian', false, false, false, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (58, 'Cyndia', 'Droogan', '793-324-9357', 'Undergrad', 'Montenegrin', false, true, false, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (59, 'Meggie', 'Carrett', '660-219-2108', 'School_of_Medicine', 'Latvian', true, true, true, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (60, 'Leighton', 'Greeson', '287-858-4436', 'Undergrad', 'Northern Sotho', false, true, true, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (61, 'Raffarty', 'Knapper', '215-879-1510', 'Faculty/Staff', 'Tsonga', true, false, true, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (62, 'Josh', 'Morpeth', '889-819-6852', 'Undergrad', 'Japanese', true, false, true, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (63, 'Beatrix', 'Twiddell', '343-133-7216', 'Faculty/Staff', 'Albanian', false, true, false, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (64, 'Pauly', 'Woodings', '207-579-7470', 'School_of_Medicine', 'Papiamento', true, true, true, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (65, 'Grethel', 'Hovie', '775-836-0177', 'School_of_Medicine', 'Luxembourgish', true, false, false, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (66, 'Aline', 'Domengue', '980-272-8484', 'Faculty/Staff', 'French', false, false, true, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (67, 'Hastie', 'Prendergrass', '851-901-6586', 'Undergrad', 'Croatian', false, true, false, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (68, 'Evie', 'Hurl', '477-127-1422', 'Alum', 'Burmese', true, true, true, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (69, 'Bartholomeus', 'Fisbey', '110-897-7790', 'School_of_Medicine', 'Guaraní', false, true, true, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (70, 'Powell', 'Makin', '382-685-3519', 'Faculty/Staff', 'Guaraní', false, false, true, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (71, 'Gray', 'Lack', '370-905-9522', 'Alum', 'Gujarati', true, true, true, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (72, 'Allan', 'Moutray Read', '347-996-5950', 'School_of_Medicine', 'Aymara', true, false, false, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (73, 'Abelard', 'Heakins', '889-849-9075', 'Faculty/Staff', 'Assamese', false, false, true, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (74, 'Teddie', 'Durrad', '301-666-6119', 'Alum', 'Marathi', true, false, false, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (75, 'Aloin', 'Cronchey', '121-641-4972', 'Undergrad', 'Tajik', true, false, false, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (76, 'Vasili', 'Crut', '360-686-0927', 'Fuqua', 'Ndebele', true, true, true, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (77, 'Trevar', 'Ible', '249-265-0141', 'Undergrad', 'Bulgarian', true, false, false, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (78, 'Harlan', 'Heintzsch', '942-419-1658', 'Fuqua', 'Finnish', true, true, false, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (79, 'Kassey', 'Battlestone', '306-251-5169', 'Undergrad', 'Luxembourgish', false, false, true, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (80, 'Cristi', 'Pedrocchi', '704-848-5683', 'School_of_Medicine', 'Māori', true, false, false, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (81, 'Berty', 'Douthwaite', '949-919-7427', 'Fuqua', 'German', true, false, false, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (82, 'Boyce', 'Aleevy', '595-333-7563', 'Fuqua', 'Estonian', false, false, false, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (83, 'Hy', 'Aime', '848-568-7948', 'Undergrad', 'Montenegrin', true, false, true, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (84, 'Stanfield', 'Alcoran', '785-793-8113', 'Alum', 'New Zealand Sign Language', false, true, true, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (85, 'Jedd', 'Folkard', '629-690-2123', 'Fuqua', 'Marathi', true, false, true, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (86, 'Benedetto', 'Boobyer', '769-717-6431', 'Faculty/Staff', 'Hindi', true, false, false, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (87, 'Fowler', 'Manns', '214-821-3152', 'Faculty/Staff', 'Northern Sotho', false, true, true, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (88, 'Iosep', 'Dunrige', '832-918-1443', 'Undergrad', 'Czech', true, false, false, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (89, 'Paolina', 'Dalla', '808-905-8103', 'Fuqua', 'Bengali', true, false, false, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (90, 'Wendye', 'Barsby', '124-667-3079', 'Alum', 'Oriya', true, false, true, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (91, 'Cilka', 'Soames', '594-551-1478', 'School_of_Medicine', 'Bulgarian', true, true, true, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (92, 'Suzanne', 'Maccrea', '530-990-9917', 'Fuqua', 'Azeri', false, false, false, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (93, 'Brynna', 'Warwick', '976-570-1820', 'Alum', 'Aymara', false, false, false, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (94, 'Arabela', 'Bramley', '466-893-7358', 'Undergrad', 'Italian', false, false, false, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (95, 'Gary', 'Alsford', '815-671-5130', 'Faculty/Staff', 'Māori', false, true, true, 'Driver');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (96, 'Caryl', 'Fradgley', '284-571-8448', 'Undergrad', 'Tajik', false, true, true, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (97, 'Desiree', 'Oxlade', '460-865-9392', 'Undergrad', 'Moldovan', true, true, false, 'Packer');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (98, 'Marsha', 'Scheffel', '895-756-3962', 'Fuqua', 'Thai', true, false, false, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (99, 'Khalil', 'Pelfer', '556-429-7450', 'Undergrad', 'Lao', false, true, false, 'Caller');
insert into volunteer (id, first_name, last_name, phone_number, affiliation, non_english_language, first_time_volunteer, volunteering_for_credit, hipaa_training, role) values (100, 'Ellerey', 'Petrillo', '382-756-8527', 'Undergrad', 'Malayalam', false, false, false, 'Caller');
