export const Vol_data =[{
    "id": 1,
    "firstName": "Janith",
    "lastName": "Dowsey",
    "phoneNumber": "123-456-7890",
    "email": "first.last@duke.edu",  
    "language": "English",
    "type": "Caller",
    "hipaa": "yes",
    "credit": "yes"   
  }, {
    "id": 2,
    "firstName": "Olly",
    "lastName": "Sheere",
    "phoneNumber": "123-456-7890",
    "email": "first.last@duke.edu",  
    "language": "Spanish",
    "type": "Caller",
    "hipaa": "yes",
    "credit": "yes"   
  }, {
    "id": 3,
    "firstName": "Lorne",
    "lastName": "Carswell",
    "phoneNumber": "123-456-7890",
    "email": "first.last@duke.edu",  
    "language": "Spanish",
    "type": "Driver",
    "route": "A",
    "hipaa": "yes",
    "credit": "no"   
  }, {
    "id": 4,
    "firstName": "Willamina",
    "lastName": "Pearn",
    "phoneNumber": "123-456-7890",
    "email": "first.last@duke.edu",  
    "language": "English",
    "type": "Driver",
    "route": "B",
    "hipaa": "yes",
    "credit": "yes"   
  }, {
    "id": 5,
    "firstName": "Ebonee",
    "lastName": "Gozzett",
    "phoneNumber": "123-456-7890",
    "email": "first.last@duke.edu",  
    "language": "English",
    "type": "Packer",
    "hipaa": "yes",
    "credit": "no"   
  }, {
    "id": 6,
    "firstName": "Eryn",
    "lastName": "Legendr",
    "phoneNumber": "123-456-7890",
    "email": "first.last@duke.edu",  
    "language": "Spanish",
    "type": "Packer",
    "hipaa": "yes",
    "credit": "no"    
     },
  ]
  
  